name: Publish pooputil to PyPI

on:
  release: R-0.0.1
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build binary packages (.whl and .tar.gz)
      run: python -m build

    - name: Upload binaries to PyPI via Trusted Publisher
      uses: pypa/gh-action-pypi-publish@release/v1
